language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose --all
  - cargo test --verbose --all --release
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
