[package]
name = "cargo-culture"
version = "0.1.0"
authors = ["Zachary Pierce <zpierce@polysync.io>"]

[dependencies]
cargo-culture-kit = { path = "../cargo-culture-kit" }
structopt = "0.2"

[dev-dependencies]
proptest = "0.7"
tempfile = "3"
