[package]
name = "cargo-culture-kit"
version = "0.1.0"
authors = ["ZackPierce <zacharypierce@gmail.com>"]

[features]
default = []

[dependencies]
cargo_metadata = "0.5.4"
colored = "1.6"
failure = "0.1"
lazy_static = "1.0"
regex = "1"

[dev-dependencies]
tempfile = "3"
proptest = "0.7"
